"""Build local reading WOFF2 shards from Adobe SourceHanSerifSC-Regular.otf 2.003.
Usage: python subsetReaderFont.py /path/to/SourceHanSerifSC-Regular.otf
Requires fonttools[woff] (build tool only, not an application dependency).
"""
import sys
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

output = Path(__file__).resolve().parent.parent / "public/fonts/source-han-serif"
output.mkdir(parents=True, exist_ok=True)
source = TTFont(sys.argv[1])
available = set(source.getBestCmap())
# GB2312 first-level Han characters form a common shard, with Latin and punctuation.
common = set(range(0x20, 0x250)) | set(range(0x2000, 0x2070)) | set(range(0x3000, 0x3040)) | set(range(0xFF00, 0xFFF0))
for high in range(0xB0, 0xD8):
    for low in range(0xA1, 0xFF):
        try:
            common.add(ord(bytes([high, low]).decode("gb2312")))
        except UnicodeDecodeError:
            pass
common &= available
han = available & set(range(0x3400, 0xA000))
remaining = sorted(han - common)
shards = [("common", sorted(common))] + [(f"han-{i // 512:02}", remaining[i:i + 512]) for i in range(0, len(remaining), 512)]
css = ["/* Generated by scripts/subsetReaderFont.py. OFL license and provenance accompany the shards. */"]
for name, points in shards:
    font = TTFont(sys.argv[1])
    options = subset.Options()
    options.hinting = False
    options.layout_features = ["kern", "liga"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=points)
    subsetter.subset(font)
    # OFL reserved font names: modified subset uses a distinct internal family.
    for record in font["name"].names:
        if record.nameID in (1, 2, 3, 4, 6, 16, 17):
            label = "Regular" if record.nameID in (2, 17) else "WReaderReadingSerif" if record.nameID == 6 else "WReader Reading Serif"
            record.string = label.encode(record.getEncoding())
    font.flavor = "woff2"
    font.save(output / f"{name}.woff2")
    ranges = []
    start = end = points[0]
    for point in points[1:]:
        if point == end + 1:
            end = point
        else:
            ranges.append(f"U+{start:X}-{end:X}" if start != end else f"U+{start:X}")
            start = end = point
    ranges.append(f"U+{start:X}-{end:X}" if start != end else f"U+{start:X}")
    css.append('@font-face { font-family: "WReader Reading Serif"; font-style: normal; font-weight: 400; font-display: swap; src: url("/fonts/source-han-serif/' + name + '.woff2") format("woff2"); unicode-range: ' + ','.join(ranges) + '; }')
(output / "font.css").write_text("\n".join(css) + "\n")
print(f"{len(shards)} shards; {sum(p.stat().st_size for p in output.glob('*.woff2')):,} bytes total")
